package io.github.untactorder

import android.app.Application
import android.content.Context
import android.content.Intent
import android.os.Build
import android.widget.Toast
import com.kakao.sdk.common.KakaoSdk
import com.navercorp.nid.NaverIdLoginSDK
import io.github.untactorder.androidclient.MainActivity

class GlobalApplication : Application() {
    val KeyError = "key_error"

    override fun onCreate() {
        super.onCreate()

        // if release mode, check if the apk's key is generated by PlayStore.
        if (!isPackageSignValid(this)) {
            var intent = Intent(this, MainActivity::class.java)
            intent.putExtra(KeyError, true)
            startActivity(intent)
        }

        // init Kakao SDK
        KakaoSdk.init(this, BuildConfig.KAKAO_NATIVE_APP_KEY)

        // init Naver ID Login SDK
        //NaverIdLoginSDK.initialize(this, BuildConfig.NAVER_OAUTH_CLIENT_ID,
        //    BuildConfig.NAVER_OAUTH_CLIENT_SECRET, resources.getString(R.string.app_name))
    }

    /**
     * https://stackoverflow.com/questions/66896154/getinstallerpackagenamestring-string-is-deprecated-deprecated-in-java
     */
    fun getInstallerPackageName(context: Context): String? {
        kotlin.runCatching {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
                return context.packageManager.getInstallSourceInfo(context.packageName).installingPackageName
            } else {
                @Suppress("DEPRECATION")
                return context.packageManager.getInstallerPackageName(context.packageName)
            }
        }
        return null
    }

    fun isPackageSignValid(context: Context): Boolean {
        // https://philosopher-chan.tistory.com/372
        if (!BuildConfig.DEBUG) {
            val packageName = getInstallerPackageName(context)
            // 플레이 스토어에서 설치했을 경우 "com.android.vending" 으로 시작
            if (packageName == null || !packageName.startsWith("com.android.vending")) {
                Toast.makeText(context, R.string.error_not_downloaded_from_playstore, Toast.LENGTH_LONG).show()
                return false
            }
        }
        return true
    }
}